# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Emmanuel Corrales
tagline: Software Engineer
description: "Emmanuel Corrales is a Software Engineer with a passion for developing
software. He has a degree in Computer Science and loves clean and well-tested
code. He is currently working with Javascript on MERN stack and Ruby on Rails
applications. He is also an experienced Android Developer and Enterpise
Applications Developer(.Net and Spring). He is a linux enthusiast and his
favorite tool is the terminal. He codes with it, works with it, lives with it
and will probably not survive without it. He is a big fan of open source and is
always trying to learn something new."
url: "https://emcorrales.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
theme: jekyll-theme-hyde-plus
permalink: /blog/:title
paginate: 5

collections:
  cheatsheets:
    output: true

plugins:
  - jemoji

emoji:
  src: "/assets/images/"

social:
  twitter:        em_corrales
  linkedin:       emmanuelcorrales
  github:         EmmanuelCorrales
  disqus:         emmanuel-corrales

google_analytics: UA-80537045-1

author:
  name:           'Emmanuel Corrales'
  email:          contact@emmanuelcorrales.com
  url:            https://emcorrales.com
