# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Emmanuel Corrales
email: contact@emmanuelcorrales.com
description: "Hello, and welcome to my blog. My name is Emmanuel Corrales. I'm a
software developer. I made this blog so I can share my knowledge to the world
and help other software developers like me. If you are here then you must be looking
for possible solutions to your programming problems. I hope some of my post can
help you. If you have suggestions and comments please do not hesitate to contact me."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.emmanuelcorrales.com" # the base hostname & protocol for your site
twitter_username: emcorrales22
github_username:  EmmanuelCorrales
google_analytics: UA-80537045-2
disqus:
    shortname: emmanuel-corrales

# Build settings
markdown: kramdown
theme: minima
permalink: /posts/:title
