# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Emmanuel Corrales
email: contact@emmanuelcorrales.com
description: "Emmanuel Corrales is a software engineer with a passion for developing software.
 He has a degree in computer science and loves clean and well-tested code. Currently he is
 working with Javascript and Ruby on Rails applications. His favorite tool is the terminal.
 He works with it, lives with it and will probably not survive without it. He is a big fan of
 open source and is always trying to learn something new."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.emmanuelcorrales.com" # the base hostname & protocol for your site
twitter_username: emcorrales22
github_username:  EmmanuelCorrales
google_analytics: UA-80537045-2
disqus:
    shortname: emmanuel-corrales

# Build settings
markdown: kramdown
theme: minima
permalink: /posts/:title
