# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Emmanuel Corrales
tagline: DevOps Consultant and Software Engineer
description: "I am Emmanuel Corrales, you may also call me Em. I've been in the
technology industry for more than five years. I am currently working as a DevOps
Consultant for Opswerks. I am also an experienced Software Engineer who is
language agnostic. A jack of all trades guy. I'm a linux enthusiast and my
favorite tool is the terminal. I code with it, work with it, live with it and
will probably not survive without it. I am a big fan of open source and has
always been trying to learn something new."
url: "https://emcorrales.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
theme: jekyll-theme-hyde-plus
permalink: /blog/:title
paginate: 5

collections:
  cheatsheets:
    output: true

plugins:
  - jemoji
  - jekyll-gravatar
  - jekyll-sitemap

emoji:
  src: "/assets/images/"

social:
  twitter:        em_corrales
  linkedin:       emmanuelcorrales
  github:         emcorrales
  disqus:         emmanuel-corrales

google_analytics: UA-80537045-1

author:
  name:           'Emmanuel Corrales'
  email:          contact@emcorrales.com
  url:            https://emcorrales.com
