name: Deployment

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: emcorrales/action-jekyll-deploy-ghpages@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "Emmanuel M. Corrales"
        email: "contact@emcorrales.com"
        domain: emcorrales.com
