name: Deployment

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: emcorrales/action-jekyll-deploy-ghpages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        git_committer_name: "Emmanuel M. Corrales"
        git_committer_email: "contact@emcorrales.com"
        custom_domain: emcorrales.com
