name: Development CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: emcorrales/action-deploy@master
      with:
        name: "Emmanuel M. Corrales"
        email: "contact@emcorrales.com"
        url: github.com/emcorrales/blog.git
        domain: emcorrales.com
